//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int idTicket { get; set; }
        public string Ticket { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraFinal { get; set; }
        public int idUsuario { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
